export const DUMMY_DATA = [
	{
		id: 'product-1',
		name: '+5 Dexterity Vest',
		sellIn: 10,
		quality: 20,
		type: 'regular',
		image: '/images/vest.jpg',
	},
	{
		id: 'product-2',
		name: 'Aged Brie',
		sellIn: 2,
		quality: 0,
		type: 'vintage',
		image: '/images/brie.jpg',
	},
	{
		id: 'product-3',
		name: 'Elixir of the Mongoose',
		sellIn: 5,
		quality: 7,
		type: 'regular',
		image: '/images/mongoose.jpg',
	},
	{
		id: 'product-4',
		name: 'Sulfuras, Hand of Ragnaros',
		sellIn: 0,
		quality: 80,
		type: 'legendary',
		image: '/images/sulfuras.jpg',
	},
	{
		id: 'product-5',
		name: 'Sulfuras, Hand of Ragnaros',
		sellIn: -1,
		quality: 80,
		type: 'legendary',
		image: '/images/sulfuras.jpg',
	},
	{
		id: 'product-6',
		name: 'Backstage passes to a TAFKAL80ETC concert',
		sellIn: 15,
		quality: 20,
		type: 'vintage',
		image: '/images/concert.jpg',
	},
	{
		id: 'product-7',
		name: 'Backstage passes to a TAFKAL80ETC concert',
		sellIn: 10,
		quality: 49,
		type: 'vintage',
		image: '/images/concert.jpg',
	},
	{
		id: 'product-8',
		name: 'Backstage passes to a TAFKAL80ETC concert',
		sellIn: 5,
		quality: 49,
		type: 'vintage',
		image: '/images/concert.jpg',
	},
	{
		id: 'product-9',
		name: 'Conjured Mana Cake',
		sellIn: 3,
		quality: 6,
		type: 'regular',
		image: '/images/cake.jpg',
	},
];
